<a href="https://colab.research.google.com/github/pulkitshringi/Colab/blob/main/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,4,1,4],[3,4,1,6]])
print(arr2D.shape)

(3, 4)


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,4,1,4],[3,4,1,6]])
print(arr2D.ndim)

2


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,4,1,4],[3,4,1,6]])
print(arr2D.size)

12


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,4,1,4],[3,4,1,6]])
print(arr2D.dtype)

int64


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,"str1","str2",4],[3,4,1,6]])
print(arr2D.dtype)

<U21


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,"str1","str2",4],[3,4,1,6]])
print(arr2D[0][0].dtype)

<U1


<h3>Filling Arrays</h3>

In [1]:
import numpy as np
arr = np.full((2,3),6) # filling 2x3 array with 6
print(arr)


[[6 6 6]
 [6 6 6]]


In [2]:
import numpy as np
arr = np.full((2,3,2),4) # filling 2 arrays of 3x2 (3rd Dimensional) with 4
print(arr)

[[[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]]


In [4]:
import numpy as np
arr = np.zeros((2,3,2)) # filling 2 arrays of 3x2 (3rd Dimensional) with 0
print(arr)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [6]:
import numpy as np
arr = np.arange(0,100,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [8]:
import numpy as np
arr = np.linspace(0,500,3) # 3 elements that are spaced evenly from 0 to 500
print(arr)

[  0. 250. 500.]


In [9]:
import numpy as  np
print(np.nan)
print(np.inf)

nan
inf


In [10]:
import numpy as np
print(np.isnan(np.nan))
print(np.isinf(np.inf))

True
True


In [16]:
import numpy as np
print(np.isnan(np.sqrt(-1)))

True


<ipython-input-16-8eaa5e2b8158>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))
