<a href="https://colab.research.google.com/github/pulkitshringi/Colab/blob/main/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,4,1,4],[3,4,1,6]])
print(arr2D.shape)

(3, 4)


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,4,1,4],[3,4,1,6]])
print(arr2D.ndim)

2


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,4,1,4],[3,4,1,6]])
print(arr2D.size)

12


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,4,1,4],[3,4,1,6]])
print(arr2D.dtype)

int64


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,"str1","str2",4],[3,4,1,6]])
print(arr2D.dtype)

<U21


In [ ]:
import numpy as np
arr2D = np.array([[1,2,3,4],[2,"str1","str2",4],[3,4,1,6]])
print(arr2D[0][0].dtype)

<U1


<h3>Filling Arrays</h3>

In [ ]:
import numpy as np
arr = np.full((2,3),6) # filling 2x3 array with 6
print(arr)


[[6 6 6]
 [6 6 6]]


In [ ]:
import numpy as np
arr = np.full((2,3,2),4) # filling 2 arrays of 3x2 (3rd Dimensional) with 4
print(arr)

[[[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]]


In [ ]:
import numpy as np
arr = np.zeros((2,3,2)) # filling 2 arrays of 3x2 (3rd Dimensional) with 0
print(arr)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
import numpy as np
arr = np.arange(0,100,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
import numpy as np
arr = np.linspace(0,500,3) # 3 elements that are spaced evenly from 0 to 500
print(arr)

[  0. 250. 500.]


In [ ]:
import numpy as  np
print(np.nan)
print(np.inf)

nan
inf


In [ ]:
import numpy as np
print(np.isnan(np.nan))
print(np.isinf(np.inf))

True
True


In [ ]:
import numpy as np
print(np.isnan(np.sqrt(-1)))

True


<ipython-input-16-8eaa5e2b8158>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))


In [1]:
arr = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(arr)

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


In [3]:
import numpy as np
temp = [1,2,3]
arr = np.array(temp)
print(arr)

[1 2 3]


In [12]:
import numpy as np
l1 = [1,2,3,4,5]
l2 = np.array(l1);
print("Numpy array :",l2/l2)

Numpy array : [1. 1. 1. 1. 1.]


In [14]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(np.sqrt(arr))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [15]:
import numpy as np
arr = np.array([1,2,3])
arr = np.append(arr,[6,9])
print(arr)

[1 2 3 6 9]


In [18]:
import numpy as np
arr = np.array([1,2,3])
arr =np.insert(arr,1,[6,9])
print(arr)

[1 6 9 2 3]


In [19]:
import numpy as np
arr = np.array([1,2,3])
arr = np.delete(arr,1)
print(arr)

[1 3]


In [24]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [26]:
import numpy as np
arr1 = [[1,2],[3,4]]
arr2 = [[10,11],[12,13]]
arr = np.concatenate((arr1,arr2),axis=1) # will be merged as columns
print(arr)

[[ 1  2 10 11]
 [ 3  4 12 13]]


In [31]:
import numpy as np
arr1 = [[1,2],[3,4]]
arr2 = [[10,11],[12,13]]
arr = np.hstack((arr1,arr2))
print(arr)
print(arr.shape)

[[ 1  2 10 11]
 [ 3  4 12 13]]
(2, 4)


In [33]:
import numpy as np
rand = np.random.randint(100) # random no from 0 to 100
print(rand)

78


In [36]:
import numpy as np
rand = np.random.randint(90,100,size=(2,2,3))
print(rand)

[[[99 99 95]
  [96 94 98]]

 [[94 95 98]
  [94 96 97]]]
